config/routes.rb
Rails.application.routes.draw do
  get    '/',                                to: 'welcome#index',                   as: 'root'
  get    '/test_invite',                     to: 'welcome#test_invite',             as: 'test_invite'

  get    '/admin',                           to: 'admin#index',                     as: 'admin_index'
  get    '/admin/test_exception',            to: 'admin#test_exception'
  get    '/admin/email',                     to: 'admin#compose_email',             as: 'admin_compose_email'
  post   '/admin/email',                     to: 'admin#send_email',                as: 'admin_send_email'
  get    '/admin/login',                     to: 'admin#login',                     as: 'admin_login'
  post   '/admin/login',                     to: 'admin#process_login',             as: 'admin_process_login'
  get    '/admin/logout',                    to: 'admin#logout',                    as: 'admin_logout'

  get    '/signup',                          to: 'users#new',                       as: 'signup'
  get    '/users',                           to: 'users#index',                     as: 'users'
  post   '/user',                            to: 'users#create',                    as: 'create_user'
  get    '/user/confirm_email',              to: 'users#confirm_email',             as: 'confirm_email'
  get    '/user/deleted',                    to: 'users#deleted',                   as: 'deleted_user'
  get    '/user/new',                        to: 'users#new',                       as: 'new_user'
  get    '/user/recover_account',            to: 'users#recover_account',           as: 'recover_account'
  post   '/user/recover_account',            to: 'users#recover_account_submit',    as: 'recover_account_submit'
  get    '/user/revert_email/:code',         to: 'users#revert_email',              as: 'revert_email'
  get    '/user/:uuid',                      to: 'users#show',                      as: 'user'
  get    '/user/:uuid/admin',                to: 'users#admin',                     as: 'admin_user'
  get    '/user/:uuid/edit',                 to: 'users#edit',                      as: 'edit_user'
  get    '/user/:uuid/events',               to: 'users#events',                    as: 'user_events'
  get    '/user/:uuid/confirm',              to: 'users#confirm_user',              as: 'confirm_user'
  patch  '/user/:uuid',                      to: 'users#update',                    as: 'update_user'
  get    '/user/:uuid/delete',               to: 'users#delete',                    as: 'delete_user'
  get    '/user/:uuid/delete/admin',         to: 'users#admin_delete',              as: 'admin_delete_user'
  get    '/user/:uuid/resend_confirmation',  to: 'users#resend_confirmation',       as: 'reconfirm_user_confirmation'

  get    '/events',                          to: 'events#index',                    as: 'events'
  post   '/event',                           to: 'events#create',                   as: 'create_event'
  get    '/event/clone',                     to: 'events#clone',                    as: 'clone_event'
  get    '/event/new',                       to: 'events#new',                      as: 'new_event'
  get    '/event/invite_user',               to: 'events#invite_user',              as: 'invite_user'
  get    '/event/:uuid',                     to: 'events#show',                     as: 'event'
  get    '/event/:uuid/rsvp/:user_uuid',     to: 'events#rsvp_old',                 as: 'event_rsvp_old'
  post   '/event/:uuid/rsvp',                to: 'events#submit_rsvp',              as: 'submit_event_rsvp'
  get    '/event/:uuid/admin',               to: 'events#admin',                    as: 'admin_event'
  get    '/event/:uuid/edit',                to: 'events#edit',                     as: 'edit_event'
  patch  '/event/:uuid',                     to: 'events#update',                   as: 'update_event'
  get    '/event/:uuid/delete',              to: 'events#delete',                   as: 'delete_event'
  delete '/event/:uuid',                     to: 'events#soft_delete',              as: 'soft_delete_event'
  get    '/event/:uuid/synidicate',          to: 'events#syndicate',                as: 'syndicate_event'
  get    '/event/:uuid/synidicate_preview',  to: 'events#syndicate_preview',        as: 'syndicate_event_preview'

  get    '/special_events',                  to: 'special_events#index',            as: 'special_events'
  post   '/special_event',                   to: 'special_events#create',           as: 'create_special_event'
  get    '/special_event/new',               to: 'special_events#new',              as: 'new_special_event'
  get    '/special_event/invite_guest',      to: 'special_events#invite_guest',     as: 'special_invite_guest'
  get    '/special_event/invite_guests',     to: 'special_events#invite_guests',    as: 'special_invite_guests'
  post   '/special_event/:uuid/add_guests',  to: 'special_events#add_guests',       as: 'special_event_add_guests'
  post   '/special_event/:uuid/rsvp',        to: 'special_events#submit_rsvp',      as: 'submit_special_event_rsvp'
  get    '/special_event/:uuid/admin',       to: 'special_events#admin',            as: 'admin_special_event'
  get    '/special_event/:uuid/edit',        to: 'special_events#edit',             as: 'edit_special_event'
  get    '/special_event/:uuid/delete',      to: 'special_events#delete',           as: 'delete_special_event'
  patch  '/special_event/:uuid',             to: 'special_events#update',           as: 'update_special_event'
  delete '/special_event/:uuid',             to: 'special_events#soft_delete',      as: 'soft_delete_special_event'

  get    '/rsvp/:identifier',                to: 'events#rsvp',                     as: 'event_rsvp'

  get    '/addresses',                       to: 'addresses#index',                 as: 'addresses'
  post   '/address',                         to: 'addresses#create',                as: 'create_address'
  get    '/address/new',                     to: 'addresses#new',                   as: 'new_address'
  get    '/address/:id/edit',                to: 'addresses#edit',                  as: 'edit_address'
  get    '/address/:id',                     to: 'addresses#show',                  as: 'address'
  patch  '/address/:id',                     to: 'addresses#update',                as: 'update_address'
  get    '/address/:id/delete',              to: 'addresses#delete',                as: 'delete_address'
  delete '/address/:id/destroy',             to: 'addresses#destroy',               as: 'destroy_address'

  get    '/lists',                           to: 'subscription_lists#index',        as: 'lists'
  post   '/list',                            to: 'subscription_lists#create',       as: 'create_list'
  get    '/list/new',                        to: 'subscription_lists#new',          as: 'new_list'
  get    '/list/:id/edit',                   to: 'subscription_lists#edit',         as: 'edit_list'
  get    '/list/:id',                        to: 'subscription_lists#show',         as: 'list'
  patch  '/list/:id',                        to: 'subscription_lists#update',       as: 'update_list'
  get    '/list/:id/delete',                 to: 'subscription_lists#delete',       as: 'delete_list'
  delete '/list/:id/destroy',                to: 'subscription_lists#destroy',      as: 'destroy_list'

  get    '/errors/email_already_confirmed',   to: 'errors#email_already_confirmed', as: 'email_already_confirmed'
end

app/models/user.rb
class User < ApplicationRecord
  UUID_REGEX = /\A[a-z0-9]{8}-[a-z0-9]{4}-[a-z0-9]{4}-[a-z0-9]{4}-[a-z0-9]{12}\Z/

  before_save :downcase_email_address

  has_many :subscriptions
  has_many :subscription_lists, through: :subscriptions
  has_many :syndications

  validates_inclusion_of :email_confirmed, in: [true, false]
  validates_inclusion_of :admin_confirmed, in: [true, false]

  validates :uuid, format: { with: UUID_REGEX }

  validates_presence_of :first_name
  validates_presence_of :last_name

  validates_email_format_of :email_address
  validates :email_address, presence: true,
                            uniqueness: { case_sensitive: false }

  validate :phone_number_formatter
  validate :opt_out_of_email_only_if_phone_number_present

  def is_moderator
    moderator === true
  end

  def name
    "#{first_name} #{last_name}"
  end

  def delete_phone_number_and_opt_into_emails
    self.suppress_emails = false
    self.phone_number = nil

    UserMailer.phone_number_reverted(self).deliver_now

    self.save
  end

  def opt_out_of_email_only_if_phone_number_present
    if self.suppress_emails
      unless self.phone_number && self.phone_number != ''
        errors.add(:suppress_emails, 'only allowed in the presence of a phone number')
      end
    end
  end

  def phone_number_formatter
    return if !self.phone_number

    if self.phone_number == ''
      self.phone_number = nil
      return
    end

    phone_number = self.phone_number.gsub(/\D/, '')
    unless phone_number.match(/\A\d{10}\z/)
      errors.add(:phone_number, 'is invalid')
    else
      self.phone_number = phone_number
    end
  end

  def downcase_email_address
    if self.email_address
      self.email_address.downcase!
    else # for the tests...
      ''
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_admin_login, only: [
    :index, :admin, :edit, :admin_delete, :admin_destroy, :confirm_user
  ]

  include Rails.application.routes.url_helpers

  def index
    @unconfirmed_users = User.where(email_confirmed: false).or(User.where(admin_confirmed: false)).order(:first_name, :last_name)
    confirmed_users = User.where(email_confirmed: true).and(User.where(admin_confirmed:true)).order(:first_name, :last_name)
    @confirmed_users = confirmed_users.map do |user|
      {
        uuid: user.uuid,
        name: user.name,
        preferences: get_user_preferences(user)
      }
    end
  end

  def get_user_preferences(user)
    email = "\u{1F4E7}".encode('utf-8')
    phone = "\u{1F4DE}".encode('utf-8')

    if user.suppress_emails
      phone
    elsif user.phone_number
      "#{email} / #{phone}"
    else
      email
    end
  end

  def admin
    @user = User.find_by(uuid: params[:uuid])
    @subscriptions = Subscription.where(user_id: @user).map do |s|
      SubscriptionList.find(s.subscription_list_id).name
    end

    # These numbers won't be perfect, but what in life is?
    @rsvps = Rsvp.where(user_id: @user)
    @events = Event
      .where(datetime: @user.created_at..)
      .where('deleted IS NOT TRUE')
      .where(subscription_list_id: @user.subscription_lists.map{|l| l.id})
  end

  def edit
    @user = User.find_by(uuid: params[:uuid])
    @subscriptions = Subscription.where(user_id: @user).map do |s|
      SubscriptionList.find(s.subscription_list_id).name
    end
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    @user.update(uuid: SecureRandom.uuid)
    @user.update(email_confirmed: false)
    @user.update(user_confirmed: false)
    @user.update(admin_confirmed: false)
    @user.update(email_confirmation_code: SecureRandom.hex)

    if @user.save
      params['user']['subscription_list_ids'].each do |s|
        new_subscription = SubscriptionList.where(id: s).take
        if new_subscription
          Subscription.create(user_id: @user.id,
                               subscription_list_id: new_subscription.id)
        end
      end

      send_user_confirmation_email(@user)
      send_admin_new_user_email(@user)

      (redirect_to action: :show, uuid: @user.uuid)
    else
      @user.uuid = nil
      render :new
    end
  end

  def show
    @user = User.find_by uuid: params['uuid']
  end

  def update
    @user = User.find_by uuid: params['user']['uuid']
    is_admin = !!(params['user']['admin'] == 'true' && session[:admin])
    admin_confirm_required = is_admin && params['user']['email_confirmed'] == '0' && @user['email_confirmed']
    non_admin_confirm_required = params['user']['email_address'] != @user['email_address'] && !is_admin

    if @user.update(user_params)
      Subscription.where(user_id: @user).destroy_all
      params['user']['subscription_list_ids'].each do |s|
        new_subscription = SubscriptionList.where(id: s).take
        if new_subscription
          Subscription.create(
            user_id: @user.id,
            subscription_list_id: new_subscription.id
          )
        end
      end

      if admin_confirm_required || non_admin_confirm_required
        @user.update(email_confirmation_code: SecureRandom.hex)
        @user.update(email_confirmed: false)
        if @user.save
          UserMailer.change_email_address_email(@user).deliver_now
        end
      end

      flash[:success] = 'Profile successfully updated!'

      if is_admin
        redirect_to action: :admin, uuid: @user.uuid
      else
        redirect_to action: :show, uuid: @user.uuid
      end
    else
      render :show
    end
  end

  def events
    user_uuid = params['uuid']
    @user = User.find_by({uuid: user_uuid})

    syndications = Syndication.where({user_id: @user.id})
    syndications_with_events = syndications.filter{|s| s.event != nil}

    fs, ps = syndications_with_events.partition do |s|
      s.event.datetime > DateTime.now
    end

    @future_syndications = fs.sort_by { |s| s.event.datetime }.reverse
    @past_syndications = ps.sort_by { |s| s.event.datetime }.reverse
  end

  def delete
    @user = User.find_by uuid: params['uuid']
    destroy(@user)
  end

  def destroy(user, admin = false)
    Subscription.where(user_id: @user).destroy_all
    Syndication.where(user_id: @user).destroy_all
    Rsvp.where(user_id: @user).destroy_all

    user_name = @user.name
    user_email = @user.email_address

    @user.destroy

    if admin
      redirect_to :users
    else
      send_admin_destroyed_user_email(user_name, user_email)
      redirect_to :deleted_user
    end
  end

  def admin_delete
    @user = User.find_by uuid: params['uuid']
    destroy(@user, true)
  end

  def deleted
  end

  def confirm_user
    @user = User.find_by(uuid: params[:uuid])
    @user.update(admin_confirmed: true)
    flash[:success] = 'User successfully confirmed'
    redirect_to :admin_user
  end

  def confirm_email
    @user = User.find_by email_confirmation_code: params['code']
    if @user == nil
      return(redirect_to :email_already_confirmed)
    end
    @user.update(email_backup: nil)
    @user.update(email_confirmation_code: nil)
    @user.update(email_confirmed: true)
    @user.update(user_confirmed: true)

    if @user.save
      flash[:success] = 'Thank you, your email address has been confirmed!'
      if params['admin']
        flash[:success] = 'The user\'s email address has been succesfully confirmed.'
        (redirect_to action: :admin, uuid: @user.uuid)
      else
        (redirect_to action: :show, uuid: @user.uuid)
      end
    end
  end

  def revert_email
    @user = User.find_by email_confirmation_code: params['code']
    @user.update(email_address: @user.email_backup)
    @user.update(email_backup: nil)
    @user.update(email_confirmation_code: nil)
    if @user.save
      (redirect_to :email_change_reverted)
    end
  end

  def recover_account_submit
    @user = User.find_by email_address: params['email_address']
    if @user
      UserMailer.recover_account(@user).deliver_now
    end
    render :recover_account_confirmation
  end

  def send_admin_new_user_email(user)
    UserMailer.new_user_email(user).deliver_now
  end

  def send_admin_destroyed_user_email(user_name, user_email)
    UserMailer.destroyed_user_email(user_name, user_email).deliver_now
  end

  def send_user_confirmation_email(user)
    UserMailer.confirmation_email(user).deliver_now
  end

  def resend_confirmation
    @user = User.find_by uuid: params['uuid']
    if @user.user_confirmed
      UserMailer.change_email_address_email(@user).deliver_now
    else
      send_user_confirmation_email(@user)
    end
    flash[:success] = 'Sent!'
    redirect_to action: :show, uuid: @user.uuid
  end

  private

    def user_params
      params.require(:user).permit(
        :email_address,
        :email_confirmed,
        :first_name,
        :invitation_type,
        :last_name,
        :moderator,
        :phone_number,
        :suppress_emails
      )
    end
end

app/views/users/_user_form.html.haml
#user_form.form
  - if !@user.uuid
    .notice
      <strong>Please use a name that I'll recognize.</strong> I want to make sure I know who's getting these emails. &#9786;

  - elsif !@user.email_confirmed
    .notice.warning
      <strong>You have not confirmed your email address.</strong>
      Please check your inbox for a confirmation email.
      = link_to 'Resend?', { controller: 'users', action: 'resend_confirmation', uuid: @user.uuid }

  = form_for(user, url: submit_url) do |f|
    - if @user.errors.any?
      %ul#errors.notice.warning
        - @user.errors.full_messages.each do |err|
          %li
            =err

    .option.text
      = f.label :first_name
      = f.text_field :first_name

    .option.text
      = f.label :last_name
      = f.text_field :last_name

    .option.text
      = f.label :email_address
      = f.text_field :email_address

    .option.text
      = f.label :phone_number
      = f.text_field :phone_number, placeholder: "6175551234"

    .option
      =check_box :user, :suppress_emails
      =f.label "Opt out of invitation emails (only text)"
    %br

    = f.hidden_field :invitation_type, :value => 1

    - if admin
      .option
        =check_box :user, :email_confirmed
        =f.label "User's email address is confirmed"
      %br

    - if admin
      .option
        =check_box :user, :moderator
        =f.label "User is moderator"
      %br

    = f.hidden_field :admin, :value => admin

    .checkboxes
      = collection_check_boxes :user,
                               :subscription_list_ids,
                               SubscriptionList.all,
                               :id,
                               lambda {|l| "#{l.name} (#{l.description})"} do |b|
        .option
          = b.check_box
          = b.label

    - if user.uuid
      = f.hidden_field :uuid, :value => user.uuid
    .actions
      = f.submit 'Submit'
      - if user.uuid
        = link_to 'Delete My Account', { controller: 'users', action: 'delete', uuid: user.uuid }, id: 'delete'
      - else
        = link_to "Lost access to your account?", { controller: 'users', action: 'recover_account' }, id: 'recover'

app/views/users/admin.html.haml
= render partial: 'admin_toolbar'

%h2 #{@user.name()} (#{@user.admin_confirmed ? bool_to_unicode(@user.admin_confirmed) : link_to("Confirm?", confirm_user_path(@user.uuid))})

- if @user.is_moderator
  .mod-badge
    %p Moderator

%div
  %strong Email Address:
  = "#{@user.email_address} (#{bool_to_unicode(@user.email_confirmed)})"
  - if not @user.email_confirmed
    (#{link_to("Force confirm?", confirm_email_path(@user, code: @user.email_confirmation_code, admin: true))})
  - if @user.suppress_emails
    (Opted Out)

%div
  %strong Phone Number:
  = "#{@user.phone_number}"

%div
  %strong Subscriptions:
  %ul
    - @subscriptions.each do |s|
      %li
        = s
%div
  %strong Activity:
  %ul
    %li
      Account age: #{DateTime.now.year * 12 + DateTime.now.month - (@user.created_at.year * 12 + @user.created_at.month)} months
    - if @events.count > 0
      %li
        Responses: #{(@rsvps.count * 1.0 / @events.count * 100).round}% (#{@rsvps.count}/#{@events.count})
      %li
        Attendance: #{(@rsvps.where(response: 1..).count * 1.0 / @events.count * 100).round}% (#{@rsvps.where(response: 1..).count}/#{@events.count})
    - else
      %li
        Responses: N/A
      %li
        Attendance: N/A

.form
  .actions
    = link_to 'Edit', { controller: 'users', action: 'edit', uuid: @user.uuid }
    = link_to 'Delete this user', { controller: 'users', action: 'admin_delete', uuid: @user.uuid }, id: 'delete'

app/views/users/delete.html.haml
%p
  = link_to 'Back', controller: 'users', action: 'edit', uuid: @user.uuid

%strong Delete user: #{@user.name} (#{@user.email_address})?

%p
  %em This will delete all record of the above user in the database. You may create a new account afterward.
= button_to 'Delete', { controller: 'users', action: 'destroy', uuid: @user.uuid}, {method: :delete, id: 'delete-confirm'}

app/views/users/delete_user_from_email.html.haml
%strong Delete user: #{@user.email_address}?

%p
  %em This will delete all record of the above user in the database. You may create a new account afterward.
= button_to 'Delete', { controller: 'users', action: 'destroy', code: @user.email_confirmation_code}, {method: :delete, id: 'delete-confirm'}

app/views/users/deleted.html.haml
%strong Your account and all associated records have been deleted.
.cta
  = link_to 'Sign up again?', controller: 'users', action: 'new'

app/views/users/edit.html.haml
= render partial: 'admin_toolbar'

%p
  = link_to 'Back', { controller: 'users', action: 'admin', uuid: @user.uuid }

%h1 Manage membership for #{@user.name} (#{@user.email_address})

= render partial: 'user_form', locals: { user: @user, submit_url: update_user_path, admin: true }

app/views/users/email_confirmed.html.haml
%h1 Thank you for confirming your email!
To manage your account and subscriptions, please click #{link_to 'here', { controller: 'users', action: 'edit', uuid: @user.uuid }}.

app/views/users/email_not_confirmed.html.haml
%h1 Uh oh. Something went wrong with the confirmation.
- if @user
  Maybe you truncated the URL? Please check your confirmation email and try again.
- else
  %div Either you really messed this one up, or something's really wrong with the site.
  %div Please try again, and if this persists please let me know.

app/views/users/events.html.haml
%h1 Events for #{@user.name} (#{@user.email_address})

%h2 Upcoming Events

%table.events
  %thead
    %tr
      %th Date
      %th List
      %th Description
      %th RSVP

  %tbody
    - @future_syndications.each do |s|
      %tr
        %td
          = s.event.datetime.strftime('%Y-%m-%d')
        %td
          = SubscriptionList.find(s.event.subscription_list_id).name
        %td.wide
          %span.wide-outer-span
            %span.wide-inner-span
              = s.event.description
        %td.center
          - rsvp = Rsvp.find_by(event_id: s.event.id, user_id: @user.id)&.get_rsvp_as_string || 'Here'
          = link_to rsvp, controller: 'events', action: 'rsvp', identifier: s.identifier

%h2 Past Events

%table.events
  %thead
    %tr
      %th Date
      %th List
      %th Description
      %th RSVP

  %tbody
    - @past_syndications.each do |s|
      %tr
        %td
          = s.event.datetime.strftime('%Y-%m-%d')
        %td
          = SubscriptionList.find(s.event.subscription_list_id).name
        %td.wide
          %span.wide-outer-span
            %span.wide-inner-span
              = s.event.description
        %td.center
          = Rsvp.find_by(event_id: s.event.id, user_id: @user.id)&.get_rsvp_as_string || '-'

app/views/users/index.html.haml
= render partial: 'admin_toolbar'

- if @unconfirmed_users
  %h2 Unconfirmed Users

  %table.users
    %thead
      %tr
        %th Name
        %th #{"\u{1F4E7}".encode('utf-8')}
        %th #{"\u{1F512}".encode('utf-8')}

    %tbody
      - @unconfirmed_users.each do |user|
        %tr{class: !user.admin_confirmed ? 'not-admin' : !user.email_confirmed ? 'not-email' : ''}
          %td
            = link_to user.name, { controller: 'users', action: 'admin', uuid: user.uuid }
          %td.center
            = bool_to_unicode(user.email_confirmed)
          %td.center
            = bool_to_unicode(user.admin_confirmed)

%h2 Confirmed Users

%table.users
  %thead
    %tr
      %th Name
      %th Notification Preferences

  %tbody
    - @confirmed_users.each do |user|
      %tr
        %td
          = link_to user[:name], { controller: 'users', action: 'admin', uuid: user[:uuid] }
        %td.center
          = user[:preferences]

app/views/users/new.html.haml
%h1 Subscribe to #{ENV.fetch("MAILING_LIST_NAME")}?

= render partial: 'user_form', locals: { user: @user, submit_url: create_user_path, admin: false }

app/views/users/recover_account.html.haml
%h1 Recover your account for #{ENV["MAILING_LIST_NAME"]}?

= form_tag(recover_account_path, method: 'post') do |f|
  = label_tag :email_address, 'Email Address:'
  = text_field_tag :email_address
  = submit_tag "Submit"

app/views/users/recover_account_confirmation.html.haml
If an account with that email address exists, we will send it an email with a link to the account page.

app/views/users/show.html.haml
%h1 Manage membership for #{@user.name} (#{@user.email_address})

- if @user.is_moderator
  .mod-badge
    %p Moderator

= render partial: 'user_form', locals: { user: @user, submit_url: update_user_path, admin: false }