config/routes.rb
Rails.application.routes.draw do
  get    '/',                                to: 'welcome#index',                   as: 'root'
  get    '/test_invite',                     to: 'welcome#test_invite',             as: 'test_invite'

  get    '/admin',                           to: 'admin#index',                     as: 'admin_index'
  get    '/admin/test_exception',            to: 'admin#test_exception'
  get    '/admin/email',                     to: 'admin#compose_email',             as: 'admin_compose_email'
  post   '/admin/email',                     to: 'admin#send_email',                as: 'admin_send_email'
  get    '/admin/login',                     to: 'admin#login',                     as: 'admin_login'
  post   '/admin/login',                     to: 'admin#process_login',             as: 'admin_process_login'
  get    '/admin/logout',                    to: 'admin#logout',                    as: 'admin_logout'

  get    '/signup',                          to: 'users#new',                       as: 'signup'
  get    '/users',                           to: 'users#index',                     as: 'users'
  post   '/user',                            to: 'users#create',                    as: 'create_user'
  get    '/user/confirm_email',              to: 'users#confirm_email',             as: 'confirm_email'
  get    '/user/deleted',                    to: 'users#deleted',                   as: 'deleted_user'
  get    '/user/new',                        to: 'users#new',                       as: 'new_user'
  get    '/user/recover_account',            to: 'users#recover_account',           as: 'recover_account'
  post   '/user/recover_account',            to: 'users#recover_account_submit',    as: 'recover_account_submit'
  get    '/user/revert_email/:code',         to: 'users#revert_email',              as: 'revert_email'
  get    '/user/:uuid',                      to: 'users#show',                      as: 'user'
  get    '/user/:uuid/admin',                to: 'users#admin',                     as: 'admin_user'
  get    '/user/:uuid/edit',                 to: 'users#edit',                      as: 'edit_user'
  get    '/user/:uuid/events',               to: 'users#events',                    as: 'user_events'
  get    '/user/:uuid/confirm',              to: 'users#confirm_user',              as: 'confirm_user'
  patch  '/user/:uuid',                      to: 'users#update',                    as: 'update_user'
  get    '/user/:uuid/delete',               to: 'users#delete',                    as: 'delete_user'
  get    '/user/:uuid/delete/admin',         to: 'users#admin_delete',              as: 'admin_delete_user'
  get    '/user/:uuid/resend_confirmation',  to: 'users#resend_confirmation',       as: 'reconfirm_user_confirmation'

  get    '/events',                          to: 'events#index',                    as: 'events'
  post   '/event',                           to: 'events#create',                   as: 'create_event'
  get    '/event/clone',                     to: 'events#clone',                    as: 'clone_event'
  get    '/event/new',                       to: 'events#new',                      as: 'new_event'
  get    '/event/invite_user',               to: 'events#invite_user',              as: 'invite_user'
  get    '/event/:uuid',                     to: 'events#show',                     as: 'event'
  get    '/event/:uuid/rsvp/:user_uuid',     to: 'events#rsvp_old',                 as: 'event_rsvp_old'
  post   '/event/:uuid/rsvp',                to: 'events#submit_rsvp',              as: 'submit_event_rsvp'
  get    '/event/:uuid/admin',               to: 'events#admin',                    as: 'admin_event'
  get    '/event/:uuid/edit',                to: 'events#edit',                     as: 'edit_event'
  patch  '/event/:uuid',                     to: 'events#update',                   as: 'update_event'
  get    '/event/:uuid/delete',              to: 'events#delete',                   as: 'delete_event'
  delete '/event/:uuid',                     to: 'events#soft_delete',              as: 'soft_delete_event'
  get    '/event/:uuid/synidicate',          to: 'events#syndicate',                as: 'syndicate_event'
  get    '/event/:uuid/synidicate_preview',  to: 'events#syndicate_preview',        as: 'syndicate_event_preview'

  get    '/special_events',                  to: 'special_events#index',            as: 'special_events'
  post   '/special_event',                   to: 'special_events#create',           as: 'create_special_event'
  get    '/special_event/new',               to: 'special_events#new',              as: 'new_special_event'
  get    '/special_event/invite_guest',      to: 'special_events#invite_guest',     as: 'special_invite_guest'
  get    '/special_event/invite_guests',     to: 'special_events#invite_guests',    as: 'special_invite_guests'
  post   '/special_event/:uuid/add_guests',  to: 'special_events#add_guests',       as: 'special_event_add_guests'
  post   '/special_event/:uuid/rsvp',        to: 'special_events#submit_rsvp',      as: 'submit_special_event_rsvp'
  get    '/special_event/:uuid/admin',       to: 'special_events#admin',            as: 'admin_special_event'
  get    '/special_event/:uuid/edit',        to: 'special_events#edit',             as: 'edit_special_event'
  get    '/special_event/:uuid/delete',      to: 'special_events#delete',           as: 'delete_special_event'
  patch  '/special_event/:uuid',             to: 'special_events#update',           as: 'update_special_event'
  delete '/special_event/:uuid',             to: 'special_events#soft_delete',      as: 'soft_delete_special_event'

  get    '/rsvp/:identifier',                to: 'events#rsvp',                     as: 'event_rsvp'

  get    '/addresses',                       to: 'addresses#index',                 as: 'addresses'
  post   '/address',                         to: 'addresses#create',                as: 'create_address'
  get    '/address/new',                     to: 'addresses#new',                   as: 'new_address'
  get    '/address/:id/edit',                to: 'addresses#edit',                  as: 'edit_address'
  get    '/address/:id',                     to: 'addresses#show',                  as: 'address'
  patch  '/address/:id',                     to: 'addresses#update',                as: 'update_address'
  get    '/address/:id/delete',              to: 'addresses#delete',                as: 'delete_address'
  delete '/address/:id/destroy',             to: 'addresses#destroy',               as: 'destroy_address'

  get    '/lists',                           to: 'subscription_lists#index',        as: 'lists'
  post   '/list',                            to: 'subscription_lists#create',       as: 'create_list'
  get    '/list/new',                        to: 'subscription_lists#new',          as: 'new_list'
  get    '/list/:id/edit',                   to: 'subscription_lists#edit',         as: 'edit_list'
  get    '/list/:id',                        to: 'subscription_lists#show',         as: 'list'
  patch  '/list/:id',                        to: 'subscription_lists#update',       as: 'update_list'
  get    '/list/:id/delete',                 to: 'subscription_lists#delete',       as: 'delete_list'
  delete '/list/:id/destroy',                to: 'subscription_lists#destroy',      as: 'destroy_list'

  get    '/errors/email_already_confirmed',   to: 'errors#email_already_confirmed', as: 'email_already_confirmed'
end

app/models/event.rb
class Event < ApplicationRecord
  include Rails.application.routes.url_helpers

  belongs_to :subscription_list

  has_one :address

  has_many :users, through: :syndications
  has_many :rsvps

  validate :check_attendance_below_limit
  validate :check_end_after_start
  validates :datetime, presence: true, uniqueness: true
  validates :datetime_end, presence: true
  validates :description, presence: true

  def attendees
    Rsvp.where(event_id: id).where('response > ?', 0).pluck(:response).reduce(:+) || 0
  end

  def maybes
    Rsvp.where(event_id: id).where('response = ?', 0).count || 0
  end

  def nopes
    Rsvp.where(event_id: id).where('response = ?', -1).count || 0
  end

  def create_ics(attendee, rsvp_url)
    ics_description =
    <<~EOS
      RSVP Here: #{rsvp_url}

      #{description}
    EOS

    cal = Icalendar::Calendar.new
    cal.event do |e|
      e.dtstart     = datetime.utc.strftime('%Y%m%dT%H%M%SZ')
      e.dtend       = datetime_end.utc.strftime('%Y%m%dT%H%M%SZ')
      e.attendee    = "mailto:#{attendee.email_address}"
      e.summary     = subscription_list.name
      e.location    = Address.find(address_id).formatted_full_one_line
      e.organizer   = "mailto:#{ENV.fetch('EVENT_ORGANIZER_USER')}@#{ENV.fetch('EMAIL_DOMAIN')}"
      e.description = ics_description
    end

    # Using 'REQUEST' means that when the recipient selects a response it will
    # get emailed back to the organizer email address. Make sure that address
    # can receive mail or else the user will get a bounceback. If you don't
    # want this behavior, you can change the method to 'PUBLISH'. Email clients
    # will add an "Add this event to your calendar" button instead of
    # "Yes/No/Maybe" RSVP buttons
    cal.ip_method = 'PUBLISH'
    cal.to_ical
  end

  private

    def check_attendance_below_limit
      if capacity && attendees >= capacity
        errors.add(:capacity, 'has been reached!')
      end
    end

    def check_end_after_start
      if datetime_end < datetime
        errors.add(:datetime_end, 'is before start')
      end
    end
end

app/controllers/event_controller.rb
class EventController < ApplicationController
  def index
    @events = Event.all.order(datetime: :desc)
    @upcoming_events = @events.select{|e| e.datetime > DateTime.now}
    @past_events = @events.select{|e| e.datetime < DateTime.now}
  end

  def new
    @event = Event.new
  end

  def create
    @event = Event.new(event_params)
    @event.uuid = SecureRandom.uuid

    event_time = params['event']['datetime'].split(/[- :]/).map{|n| n.to_i}
    @event.datetime = DateTime.new(*event_time)

    if @event.save
      redirect_to action: :manage, uuid: @event.uuid
    else
      @event.uuid = nil
      render :new
    end
  end

  def edit
    @event = Event.find_by uuid: params['uuid']
  end

  def show
    @event = Event.find_by uuid: params['uuid']

    subscribers = Subscriber
      .includes(:subscription_lists)
      .where(subscription_lists: {id: @event.subscription_list_id})

    confirmed, @unconfirmed = subscribers.partition do |s|
      s.email_confirmed and s.admin_confirmed
    end

    @invited, @not_invited = confirmed.partition do |s|
      Syndication.where(event_id: @event, subscriber_id: s).count > 0
    end
  end

  def syndicate
    @event = Event.find_by uuid: params['uuid']
  end

  def update
    @event = Event.find_by uuid: params['event']['uuid']

    if @event.update(event_params)
      flash[:success] = 'Event successfully updated!'
      redirect_to action: :index
    else
      render :manage
    end
  end

  def delete
    @event = Event.find_by uuid: params[:uuid]
  end

  def destroy
    @event = Event.find_by uuid: params['uuid']
    @event.destroy
    flash[:success] = 'Event successfully deleted!'
    redirect_to action: :index
  end

  private

  def event_params
    params.require(:event).permit(
      :capacity,
      :datetime,
      :description,
      :subscription_list_id,
      :uuid
    )
  end
end

app/views/events/_event_form.html.haml
= javascript_include_tag 'event-form'

#event_form.form
  = form_for(event, url: submit_url) do |f|
    - if @event.errors.any?
      %ul#errors
        - @event.errors.full_messages.each do |err|
          %li
            =err

    .option.text
      = f.label "Start"
      = f.text_field :datetime

    .option.text
      = f.label "End"
      = f.text_field :datetime_end

    .option.text
      = f.label :address
      = f.select :address_id, options_for_select(Address.all.collect { |a| [a.formatted_full_one_line, a.id] }, @event.address_id || nil), { include_blank: true }

    .option.text
      = f.label :capacity
      = f.text_field :capacity

    .option.text.area
      = f.label :description
      = f.text_area :description

    -if not edit
      .radios
        = collection_radio_buttons :event,
                                   :subscription_list_id,
                                   SubscriptionList.all,
                                   :id,
                                   lambda {|l| "#{l.name} (#{l.description})"} do |b|
          .option
            = b.radio_button
            = b.label

    - if edit
      =check_box_tag :suppress_email
      =f.label "Supress update email"

    - if event.uuid
      = f.hidden_field :uuid, :value => event.uuid
    .actions
      = f.submit 'Submit'
      - if event.uuid
        = link_to 'Delete Event', { controller: 'events', action: 'delete', uuid: event.uuid }, id: 'delete'

app/views/events/_event_moderator_information.html.haml
-# Sorry about this huge, gross table.
%table
  - rsvps = Rsvp.where(event_id: @event.id).sort_by { |r| r.user.first_name }
  %tr.section-header
    %td{colspan: 99} Responsed
  - if rsvps.count > 0
    %tr.header-row
      %td Name
      %td Response
    - rsvps.each do |r|
      - user = User.find(r.user_id)
      %tr{class: ['rsvp', Rsvp::RESPONSE_STRINGS_BY_VALUE[@existing_rsvp_values[r.user_id]]]}
        %td
          = user.name
        %td
          = Rsvp::RESPONSE_STRINGS_BY_VALUE[@existing_rsvp_values[r.user_id]]
  - else
    %tr
      %td.center{colspan: 99} No RSVPs

  %tr.section-header
    %td{colspan: 99} Invited (But Not Responded)
  - if @invited.count > 0
    %tr.header-row
      %td{colspan: 2} Name
    - @invited.each do |user|
      %tr
        %td{colspan: 2}
          = user.name
  - else
    %tr
      %td.center{colspan: 99} No Users

app/views/events/_event_public_information.html.haml
%p
  %strong Date:
  = event.datetime.strftime("%A, %B #{event.datetime.day.ordinalize}")

%p
  %strong Time:
  = event.datetime.strftime('%l:%M %p')

- if @address
  %p
    %strong Address:
    %a{href: @address.google_maps_link}
      #{@address.formatted_full_one_line}

  - if @address.special_instructions && @address.special_instructions.length > 0
    %p
      %strong Address Instructions:
      = @address.special_instructions

%div
  %strong Description:
  %div
    = event.description.gsub("\n", "<br />").html_safe

- if event.capacity
  %p
    %strong Capacity:
    = "#{event.capacity}"

- if @attendees
  %p
    %strong Responses:
    - @attendees.each do |attendee|
      %div
        = "  • #{attendee}"
- else
  %p
    %strong Responses:
    - if event.attendees > 0
      %br
      %span
        = "• Yes: #{event.attendees}"
    - if event.maybes > 0
      %br
      %span
        = "• Maybe: #{event.maybes}"

app/views/events/_event_table.html.haml
- simple = false if local_assigns[:simple].nil?

%table.events
  %thead
    %tr
      %th Date
      - if !simple
        %th Time
      %th List
      %th Description
      - if !simple
        %th Address
      %th RSVP
      - if !simple
        %th Show
      - if editable
        %th.edit Edit
      - if !simple
        %th Clone

  %tbody
    - events.each do |e|
      %tr
        %td
          = e.datetime.strftime('%Y-%m-%d')
        - if !simple
          %td
            = e.datetime.strftime('%l:%M %p')
        %td
          = SubscriptionList.find(e.subscription_list_id).name
        %td.wide
          %span.wide-outer-span
            %span.wide-inner-span
              = e.description
        - if !simple
          %td.wide
            - if e.address_id
              = Address.find(e.address_id).address_line_1
        %td.center
          %span{"title" => "Confirmed: #{e.attendees}, Maybe: #{e.maybes}"}
            - attendees = "#{e.attendees}(#{e.maybes})#{e.capacity && ("/#{ e.capacity}")}"
            - if simple
              = link_to "#{attendees}", { controller: 'events', action: 'admin', uuid: e.uuid }
            - if !simple
              #{attendees}
        - if !simple
          %td.center
            = link_to 'Show', { controller: 'events', action: 'admin', uuid: e.uuid }
        - if editable
          %td.edit
            = link_to 'Edit', { controller: 'events', action: 'edit', uuid: e.uuid }
        - if !simple
          %td.center
            = link_to 'Clone', { controller: 'events', action: 'clone', uuid: e.uuid }, method: :post

app/views/events/admin.html.haml
= render partial: 'admin_toolbar'

%p
  = link_to 'Back', controller: 'events', action: 'index'
  = link_to 'Edit', { controller: 'events', action: 'edit', uuid: @event.uuid }

%div
  %strong Public Link:
  = link_to 'Here', { controller: 'events', action: 'show', uuid: @event.uuid }


%div
  %strong Date:
  = @event.datetime.strftime("%A, %B #{@event.datetime.day.ordinalize}")

%div
  %strong Time:
  = @event.datetime.strftime('%l:%M %p')

%div
  %strong End:
  = @event.datetime_end.strftime('%l:%M %p')

- if @address
  %div
    %strong Address:
    = @address.formatted_full_one_line

  %div
    %strong Special Instructions:
    - if @address.special_instructions && @address.special_instructions.length > 0
      = @address.special_instructions

%div
  %strong List:
  = SubscriptionList.find(@event.subscription_list_id).name

%div
  %strong Description:
  = simple_format @event.description, nil, wrapper_tag: 'div'

%div
  %strong Total Event Guests:
  = "#{@event.attendees} Confirmed"

%div
  %strong Total Event Maybes:
  - maybe_count = Rsvp.where(event_id: @event.id).where('response = 0').count
  = "#{pluralize(maybe_count, 'Maybe')}"

- if @event.datetime > DateTime.now and @not_invited.count > 0
  %p
    = link_to "Invite #{pluralize(@not_invited.count, 'user')}!", { controller: 'events', action: 'syndicate_preview', uuid: @event.uuid }
- elsif @event.datetime > DateTime.now and @not_invited.count == 0
  %p
    All eligible users have been invited
- else
  %p
    Cannot syndicate past events.

-# Sorry about this huge, gross table.
%table
  - rsvps = Rsvp.where(event_id: @event.id).sort_by { |r| r.user.first_name }
  %tr.section-header
    %td{colspan: 4 } Responded
  - if rsvps.count > 0
    %tr.header-row
      %td Name
      %td{colspan: 2} Email Address
      %td Response
    - rsvps.each do |r|
      - user = User.find(r.user_id)
      %tr{class: ['rsvp', Rsvp::RESPONSE_STRINGS_BY_VALUE[@existing_rsvp_values[r.user_id]]]}
        %td
          = link_to user.name, { controller: 'users', action: 'admin', uuid: user.uuid }
        %td{colspan: 2}
          = user.email_address
        %td.center
          = form_tag(submit_event_rsvp_path) do |f|
            = select_tag 'RSVP', options_for_select(@options_for_rsvp_select, @existing_rsvp_values[r.user_id]), :onchange => 'this.form.submit()'
            = hidden_field(:user, :uuid, :value => user.uuid)
            = hidden_field(:admin, :true, :value => 'true')
  - else
    %tr
      %td.center{colspan: 4} No RSVPs

  %tr.section-header
    %td{colspan: 4} Invited (But Not Responded)
  - if @invited.count > 0
    %tr.header-row
      %td Name
      %td Email Address
      %td Set Response
      %td Resend
    - @invited.each do |user|
      %tr
        %td
          = link_to user.name, { controller: 'users', action: 'admin', uuid: user.uuid }
        %td
          = user.email_address
        %td.center
          = form_tag(submit_event_rsvp_path) do |f|
            = select_tag 'RSVP', options_for_select(@options_for_rsvp_select), :onchange => 'this.form.submit()'
            = hidden_field(:user, :uuid, :value => user.uuid)
            = hidden_field(:admin, :true, :value => 'true')
        %td.center
          - if @event.datetime > DateTime.now
            = button_to 'Resend', invite_user_path, method: :get, params: { event_id: @event.id, user_id: user.id }

  - else
    %tr
      %td.center{colspan: 4} No Users

  %tr.section-header
    %td{colspan: 4} Not Invited (But Eligible)
  - if @not_invited.count > 0
    %tr.header-row
      %td Name
      %td{colspan: 2} Email Address
      %td Invite
    - @not_invited.each do |user|
      %tr
        %td
          = link_to user.name, { controller: 'users', action: 'admin', uuid: user.uuid }
        %td{colspan: 2}
          = user.email_address
        %td.center
          - if @event.datetime > DateTime.now
            = button_to 'Invite', invite_user_path, method: :get, params: { event_id: @event.id, user_id: user.id }
  - else
    %tr
      %td.center{colspan: 4} No Users

  %tr.section-header
    %td{colspan: 4} Subscribed But Ineligible For Invitation
  - if @unconfirmed.count > 0
    %tr.header-row
      %td Name
      %td{colspan: 2} Email Address
      %td Missing
      - @unconfirmed.each do |user|
        %tr
          %td
            = link_to user.name, { controller: 'users', action: 'admin', uuid: user.uuid }
          %td{colspan: 2}
            = user.email_address
          %td.relative
            -if not user.email_confirmed
              %span.absolute.unconfirmed.email{title: "User has not confirmed email address"} #{"\u{1F4E7}".encode('utf-8')}
            -if not user.admin_confirmed
              %span.absolute.unconfirmed.admin{title: "Admin has not confirmed user"} #{"\u{1F6E1}".encode('utf-8')}
  - else
    %tr
      %td.center{colspan: 4} No Users

app/views/events/delete.html.haml
= render partial: 'admin_toolbar'

%p
  = link_to 'Back', controller: 'events', action: 'edit', uuid: @event.uuid

%strong Delete event?

= render partial: 'event_public_information', locals: { event: @event }

.form
  = form_tag(soft_delete_event_path(@event.uuid), method: 'delete') do
    .option.text.area
      = label_tag :reason
      = text_area_tag :reason
    .actions
      = submit_tag 'Delete'

app/views/events/deleted.html.haml
%h1 Event Deleted

%p This event has been deleted.

app/views/events/edit.html.haml
= render partial: 'admin_toolbar'

%p
  = link_to 'Back', { controller: 'events', action: 'admin', uuid: @event.uuid }

%h1 Manage event for #{@event.datetime.strftime('%A, %B %d at %I:%M %p')}

= render partial: 'event_form', locals: { event: @event, submit_url: update_event_path, edit: true }

app/views/events/index.html.haml
= render partial: 'admin_toolbar'

%p
  = link_to 'New Event', { controller: 'events', action: 'new' }

- if @upcoming_events.length > 0
  %h2 Upcoming Events
  = render partial: 'event_table', locals: { events: @upcoming_events.reverse(), editable: true }

- if @past_events.length > 0
  %h2 Past Events
  = render partial: 'event_table', locals: { events: @past_events, editable: false }

- if @deleted_events.length > 0
  %h2 Deleted Events
  = render partial: 'event_table', locals: { events: @deleted_events, editable: false }

app/views/events/new.html.haml
= render partial: 'admin_toolbar'

%p
  = link_to 'Back', controller: 'events', action: 'index'

%h1 New Event

= render partial: 'event_form', locals: { event: @event, submit_url: create_event_path, edit: false }

app/views/events/past.html.haml
%h1 Event Over

%p This event has ended.

app/views/events/rsvp.html.haml
- if @event.capacity == @event.attendees
  .notice.warning.narrow
    <strong>This event is at capacity.</strong>

= render partial: 'event_public_information', locals: { event: @event, attendees: @attendees }

%p
  = form_with url: submit_event_rsvp_path(uuid: @event.uuid), method: :post do |form|
    %strong Your RSVP:
    = select_tag 'RSVP', options_for_select(@options_for_select, @existing_rsvp_value), :onchange => 'this.form.submit()'
    = hidden_field(:user, :uuid, :value => @user.uuid)

- if @user.moderator
  = render partial: 'event_moderator_information', locals: { even: @event }

app/views/events/show.html.haml
= render partial: 'event_public_information', locals: { event: @event }

app/views/events/syndicate_preview.html.haml
= render partial: 'admin_toolbar'

%p
  = link_to 'Back', controller: 'events', action: 'admin', uuid: @event.uuid

%h1 Invite users?

%h2 Event:
%div
  %strong Date:
  = @event.datetime.strftime("%A, %B #{@event.datetime.day.ordinalize}")

%div
  %strong Time:
  = @event.datetime.strftime('%l:%M %p')

- if @address
  %div
    %strong Address:
    = "#{@address.address_line_1}, "
    - if @address.address_line_2 && @address.address_line_2.length > 0
      = "#{@address.address_line_2}, "
    = "#{@address.city}, #{@address.state} #{@address.zip}"

  %div
    %strong Address Instructions:
    - if @address.special_instructions && @address.special_instructions.length > 0
      = @address.special_instructions

%div
  %strong List:
  = SubscriptionList.find(@event.subscription_list_id).name

%div
  %strong Description:
  = @event.description

%h2 Users:
%table
  - @users.each do |u|
    %tr
      %td #{u.name}
      %td #{u.email_address}

%br

= button_to 'Invite!', { controller: 'events', action: 'syndicate', uuid: @event.uuid}, {method: :get}