config/routes.rb
Rails.application.routes.draw do
  get    '/',                                to: 'welcome#index',                   as: 'root'
  get    '/test_invite',                     to: 'welcome#test_invite',             as: 'test_invite'

  get    '/admin',                           to: 'admin#index',                     as: 'admin_index'
  get    '/admin/test_exception',            to: 'admin#test_exception'
  get    '/admin/email',                     to: 'admin#compose_email',             as: 'admin_compose_email'
  post   '/admin/email',                     to: 'admin#send_email',                as: 'admin_send_email'
  get    '/admin/login',                     to: 'admin#login',                     as: 'admin_login'
  post   '/admin/login',                     to: 'admin#process_login',             as: 'admin_process_login'
  get    '/admin/logout',                    to: 'admin#logout',                    as: 'admin_logout'

  get    '/signup',                          to: 'users#new',                       as: 'signup'
  get    '/users',                           to: 'users#index',                     as: 'users'
  post   '/user',                            to: 'users#create',                    as: 'create_user'
  get    '/user/confirm_email',              to: 'users#confirm_email',             as: 'confirm_email'
  get    '/user/deleted',                    to: 'users#deleted',                   as: 'deleted_user'
  get    '/user/new',                        to: 'users#new',                       as: 'new_user'
  get    '/user/recover_account',            to: 'users#recover_account',           as: 'recover_account'
  post   '/user/recover_account',            to: 'users#recover_account_submit',    as: 'recover_account_submit'
  get    '/user/revert_email/:code',         to: 'users#revert_email',              as: 'revert_email'
  get    '/user/:uuid',                      to: 'users#show',                      as: 'user'
  get    '/user/:uuid/admin',                to: 'users#admin',                     as: 'admin_user'
  get    '/user/:uuid/edit',                 to: 'users#edit',                      as: 'edit_user'
  get    '/user/:uuid/events',               to: 'users#events',                    as: 'user_events'
  get    '/user/:uuid/confirm',              to: 'users#confirm_user',              as: 'confirm_user'
  patch  '/user/:uuid',                      to: 'users#update',                    as: 'update_user'
  get    '/user/:uuid/delete',               to: 'users#delete',                    as: 'delete_user'
  get    '/user/:uuid/delete/admin',         to: 'users#admin_delete',              as: 'admin_delete_user'
  get    '/user/:uuid/resend_confirmation',  to: 'users#resend_confirmation',       as: 'reconfirm_user_confirmation'

  get    '/events',                          to: 'events#index',                    as: 'events'
  post   '/event',                           to: 'events#create',                   as: 'create_event'
  get    '/event/clone',                     to: 'events#clone',                    as: 'clone_event'
  get    '/event/new',                       to: 'events#new',                      as: 'new_event'
  get    '/event/invite_user',               to: 'events#invite_user',              as: 'invite_user'
  get    '/event/:uuid',                     to: 'events#show',                     as: 'event'
  get    '/event/:uuid/rsvp/:user_uuid',     to: 'events#rsvp_old',                 as: 'event_rsvp_old'
  post   '/event/:uuid/rsvp',                to: 'events#submit_rsvp',              as: 'submit_event_rsvp'
  get    '/event/:uuid/admin',               to: 'events#admin',                    as: 'admin_event'
  get    '/event/:uuid/edit',                to: 'events#edit',                     as: 'edit_event'
  patch  '/event/:uuid',                     to: 'events#update',                   as: 'update_event'
  get    '/event/:uuid/delete',              to: 'events#delete',                   as: 'delete_event'
  delete '/event/:uuid',                     to: 'events#soft_delete',              as: 'soft_delete_event'
  get    '/event/:uuid/synidicate',          to: 'events#syndicate',                as: 'syndicate_event'
  get    '/event/:uuid/synidicate_preview',  to: 'events#syndicate_preview',        as: 'syndicate_event_preview'

  get    '/special_events',                  to: 'special_events#index',            as: 'special_events'
  post   '/special_event',                   to: 'special_events#create',           as: 'create_special_event'
  get    '/special_event/new',               to: 'special_events#new',              as: 'new_special_event'
  get    '/special_event/invite_guest',      to: 'special_events#invite_guest',     as: 'special_invite_guest'
  get    '/special_event/invite_guests',     to: 'special_events#invite_guests',    as: 'special_invite_guests'
  post   '/special_event/:uuid/add_guests',  to: 'special_events#add_guests',       as: 'special_event_add_guests'
  post   '/special_event/:uuid/rsvp',        to: 'special_events#submit_rsvp',      as: 'submit_special_event_rsvp'
  get    '/special_event/:uuid/admin',       to: 'special_events#admin',            as: 'admin_special_event'
  get    '/special_event/:uuid/edit',        to: 'special_events#edit',             as: 'edit_special_event'
  get    '/special_event/:uuid/delete',      to: 'special_events#delete',           as: 'delete_special_event'
  patch  '/special_event/:uuid',             to: 'special_events#update',           as: 'update_special_event'
  delete '/special_event/:uuid',             to: 'special_events#soft_delete',      as: 'soft_delete_special_event'

  get    '/rsvp/:identifier',                to: 'events#rsvp',                     as: 'event_rsvp'

  get    '/addresses',                       to: 'addresses#index',                 as: 'addresses'
  post   '/address',                         to: 'addresses#create',                as: 'create_address'
  get    '/address/new',                     to: 'addresses#new',                   as: 'new_address'
  get    '/address/:id/edit',                to: 'addresses#edit',                  as: 'edit_address'
  get    '/address/:id',                     to: 'addresses#show',                  as: 'address'
  patch  '/address/:id',                     to: 'addresses#update',                as: 'update_address'
  get    '/address/:id/delete',              to: 'addresses#delete',                as: 'delete_address'
  delete '/address/:id/destroy',             to: 'addresses#destroy',               as: 'destroy_address'

  get    '/lists',                           to: 'subscription_lists#index',        as: 'lists'
  post   '/list',                            to: 'subscription_lists#create',       as: 'create_list'
  get    '/list/new',                        to: 'subscription_lists#new',          as: 'new_list'
  get    '/list/:id/edit',                   to: 'subscription_lists#edit',         as: 'edit_list'
  get    '/list/:id',                        to: 'subscription_lists#show',         as: 'list'
  patch  '/list/:id',                        to: 'subscription_lists#update',       as: 'update_list'
  get    '/list/:id/delete',                 to: 'subscription_lists#delete',       as: 'delete_list'
  delete '/list/:id/destroy',                to: 'subscription_lists#destroy',      as: 'destroy_list'

  get    '/errors/email_already_confirmed',   to: 'errors#email_already_confirmed', as: 'email_already_confirmed'
end

app/models/special_event.rb
class SpecialEvent < ApplicationRecord
  include Rails.application.routes.url_helpers

  has_one :address

  has_many :special_event_guests

  validate :check_end_after_start
  validates :datetime, presence: true, uniqueness: true
  validates :datetime_end, presence: true
  validates :name, presence: true
  validates :description, presence: true

  def added
    SpecialEventGuest.where({ special_event_id: id }).count
  end

  def invited
    SpecialEventGuest.where({ special_event_id: id, invited: true }).count
  end

  def coming
    SpecialEventGuest.where(special_event_id: id).where('rsvp > ?', 0).pluck(:rsvp).reduce(:+) || 0
  end

  def invited_coming
    SpecialEventGuest.where(special_event_id: id).where('rsvp > ?', 0).count
  end

  def plus_ones
    coming - SpecialEventGuest.where(special_event_id: id).where('rsvp > ?', 0).count
  end

  def maybes
    SpecialEventGuest.where(special_event_id: id).where(rsvp: 0).count
  end

  def declined
    SpecialEventGuest.where(special_event_id: id).where(rsvp: -1).count
  end

  def unresponded
    SpecialEventGuest.where({ special_event_id: id, rsvp: -2, invited: true }).count
  end

  def create_ics(guest)
    ics_description =
    <<~EOS
      #{ActionView::Base.full_sanitizer.sanitize(description)}
    EOS

    cal = Icalendar::Calendar.new
    cal.event do |e|
      e.dtstart     = datetime.utc.strftime('%Y%m%dT%H%M%SZ')
      e.dtend       = datetime_end.utc.strftime('%Y%m%dT%H%M%SZ')
      e.attendee    = "mailto:#{guest.email_address}"
      e.summary     = name
      e.location    = Address.find(address_id).formatted_full_one_line
      e.organizer   = "mailto:#{ENV.fetch('SPECIAL_EMAIL_USER')}@#{ENV.fetch('SPECIAL_EMAIL_DOMAIN')}"
      e.description = ics_description
    end

    # Using 'REQUEST' means that when the recipient selects a response it will
    # get emailed back to the organizer email address. Make sure that address
    # can receive mail or else the user will get a bounceback. If you don't
    # want this behavior, you can change the method to 'PUBLISH'. Email clients
    # will add an "Add this event to your calendar" button instead of
    # "Yes/No/Maybe" RSVP buttons
    cal.ip_method = 'PUBLISH'
    cal.to_ical
  end

  private

    def check_end_after_start
      if datetime_end < datetime
        errors.add(:datetime_end, 'is before start')
      end
    end
end

app/controllers/special_events_controller.rb
class SpecialEventsController < ApplicationController
  before_action :require_admin_login, only: [
    :index, :new, :create, :admin, :edit, :update, :delete, :destroy, :syndicate, :invite_user
  ]

  def index
    @special_events = SpecialEvent.all.order(datetime: :desc)
    @upcoming_special_events = @special_events.select { |e| (e.datetime_end > DateTime.now) && (not e.deleted) }
    @deleted_special_events = @special_events.select { |e| e.deleted }
    @past_special_events = @special_events.select { |e| (e.datetime < DateTime.now) && !e.deleted }
  end

  def new
    @special_event = SpecialEvent.new
  end

  def create
    @special_event = SpecialEvent.new(event_params)
    @special_event.uuid = SecureRandom.uuid
    @special_event.deleted = false

    if @special_event.save
      redirect_to action: :admin, uuid: @special_event.uuid
    else
      @special_event.uuid = nil
      render :new
    end
  end

  def edit
    @special_event = SpecialEvent.find_by uuid: params['uuid']
  end

  def update
    @special_event = SpecialEvent.find_by uuid: params['special_event']['uuid']

    old_event = @special_event.attributes
    @special_event.assign_attributes(event_params)
    event_changed = @special_event.changed?

    if @special_event.save
      if event_changed
        flash[:success] = 'Event successfully updated!'
      else
        flash[:notice] = 'No changes detected.'
      end
      redirect_to action: :admin
    else
      render :edit
    end
  end

  def admin
    @special_event = SpecialEvent.find_by uuid: params['uuid']

    @options_for_rsvp_select = Rsvp::RESPONSE_STRINGS_BY_VALUE.map { |k, v| [v, k] }.insert(0, '')

    @existing_rsvp_values =
        Hash[User.all.collect {
          |u| [u.id, Rsvp.find_by(event_id: @event, user_id: u)&.response || false]
        }]

    @guests = SpecialEventGuest
      .where(special_event_id: @special_event)
      .sort_by { |g| g.email_address } || []
    @uninvited, @invited = @guests.partition do |g|
      !g.invited
    end

    bad_addresses = params['bad_addresses']
    if bad_addresses
      @bad_addresses = params['bad_addresses'].join
      flash.now[:warning] = "Some of your addresses didn't pass validation. They've been left in the input box. Try again?"
    end

    if @special_event.deleted
      flash[:warning] = 'This event has been soft deleted.'
    end
  end

  def edit
    @special_event = SpecialEvent.find_by uuid: params['uuid']
  end

  def add_guests
    @special_event = SpecialEvent.find_by uuid: params['uuid']
    addresses = params['addresses'].lines
    bad_addresses = syndicate(@special_event, addresses)
    puts bad_addresses
    redirect_to action: :admin, uuid: @special_event.uuid, bad_addresses: bad_addresses
  end

  def syndicate(special_event, addresses)
    bad_addresses = []

    addresses.each do |address|
      special_event_syndication = SpecialEventGuest.new
      special_event_syndication.email_address = address.strip
      special_event_syndication.invited = false
      special_event_syndication.rsvp = -2
      special_event_syndication.special_event = special_event

      if special_event_syndication.save
        next
      else
        bad_addresses << address
      end
    end

    bad_addresses
  end

  def check_past_or_deleted(special_event)
    if special_event.deleted
      render :deleted
      return
    end

    if special_event.datetime_end < DateTime.now
      render :past
    end
  end

  def delete
    @special_event = SpecialEvent.find_by uuid: params[:uuid]
  end

  def soft_delete
    @special_event = SpecialEvent.find_by uuid: params['uuid']
    @special_event.update(deleted: true)

    invitees = SpecialEventGuest.where({ special_event_id: @special_event, invited: true })
    invitees.each do |i|
      UserMailer.special_event_deleted(i, @special_event).deliver_now
    end

    invitee_string = ActionController::Base.helpers.pluralize(invitees.count, 'invitee')
    flash[:success] = "Special event successfully soft deleted! Notified #{invitee_string}."
    redirect_to action: :index
  end

  def invite_guest
    @special_event = SpecialEvent.find(params[:special_event_id])
    @guest = SpecialEventGuest.find_by({
      special_event_id: @special_event,
      email_address: params[:email_address],
    })
    # UserMailer.invite(@user, @special_event).deliver_now
    UserMailer.invite_special(@guest, @special_event).deliver_now
    @guest.invited = true
    @guest.save
    redirect_to action: :admin, uuid: @special_event.uuid
  end

  def invite_guests
    @special_event = SpecialEvent.find(params[:special_event_id])
    @guests = SpecialEventGuest.where({
      invited: false,
      special_event_id: @special_event,
    })
    @guests.each do |guest|
      UserMailer.invite_special(guest, @special_event).deliver_now
      guest.invited = true
      guest.save
    end
    redirect_to action: :admin, uuid: @special_event.uuid
  end

  def submit_rsvp
    special_event = SpecialEvent.find_by uuid: params[:uuid]
    rsvp_count = [params[:RSVP].to_i || 0, 0].max
    if params[:RSVP] == '0'
      # If the response was "maybe" treat it as a "yes"
      rsvp_count = 1
    end

    @guest = SpecialEventGuest.find_by({
      special_event_id: special_event,
      email_address: params[:guest][:email_address]
    })

    if params[:RSVP] == nil
      @guest.rsvp = -2
      @guest.save
    else
      @guest.rsvp = params[:RSVP].to_i
      @guest.save
    end

    redirect_to action: :admin, uuid: special_event.uuid
  end

  private

    def get_users_for_event_syndication(event)
      users = User
        .includes(:subscription_lists)
        .includes(:syndications)
        .where(users: { email_confirmed: true })
        .where(users: { admin_confirmed: true })
        .where(subscription_lists: { id: @special_event.subscription_list_id })

      # there's probably a way to do this in the above query, but this works
      @users = users.filter do |u|
        Guest.where(user_id: u, event_id: @special_event).count == 0
      end
    end

    def event_params
      params.require(:special_event).permit(
        :address_id,
        :datetime,
        :datetime_end,
        :description,
        :name,
        :uuid
      )
    end
end

app/views/special_events/_special_event_form.html.haml
= javascript_include_tag 'special-event-form'

#special_event_form.form
  = form_for(special_event, url: submit_url) do |f|
    - if @special_event.errors.any?
      %ul#errors
        - @special_event.errors.full_messages.each do |err|
          %li
            =err

    .option.text
      = f.label "Name"
      = f.text_field :name

    .option.text
      = f.label "Start"
      = f.text_field :datetime

    .option.text
      = f.label "End"
      = f.text_field :datetime_end

    .option.text
      = f.label :address
      = f.select :address_id, options_for_select(Address.all.collect { |a| [a.formatted_full_one_line, a.id] }, @special_event.address_id || nil), { include_blank: true }

    .option.text.area
      = f.label :description
      = f.text_area :description

    - if special_event.uuid
      = f.hidden_field :uuid, :value => special_event.uuid
    .actions
      = f.submit 'Submit'
      - if special_event.uuid
        = link_to 'Delete Special Event', { controller: 'special_events', action: 'delete', uuid: special_event.uuid }, id: 'delete'

app/views/special_events/_special_event_table.html.haml
- simple = false if local_assigns[:simple].nil?

%table.events
  %thead
    %tr
      %th Date
      - if !simple
        %th Time
      %th Name
      - if !simple
        %th Address
      %th RSVPs
      - if !simple
        %th Show
      - if editable
        %th.edit Edit

  %tbody
    - events.each do |e|
      %tr
        %td
          = e.datetime.strftime('%Y-%m-%d')
        - if !simple
          %td
            = e.datetime.strftime('%l:%M %p')
        %td.wide
          %span.wide-outer-span
            %span.wide-inner-span
              = e.name
        - if !simple
          %td.wide
            - if e.address_id
              = Address.find(e.address_id).address_line_1
        %td.center
          %span{"title" => "Confirmed: #{e.coming}"}
            - coming = "#{e.coming}"
            - if simple
              = link_to "#{coming}", { controller: 'special_events', action: 'admin', uuid: e.uuid }
            - if !simple
              #{coming}
        - if !simple
          %td.center
            = link_to 'Show', { controller: 'special_events', action: 'admin', uuid: e.uuid }
        - if editable
          %td.edit
            = link_to 'Edit', { controller: 'special_events', action: 'edit', uuid: e.uuid }

app/views/special_events/admin.html.haml
= render partial: 'admin_toolbar'

%p
  = link_to 'Back', controller: 'special_events', action: 'index'
  = link_to 'Edit', { controller: 'special_events', action: 'edit', uuid: @special_event.uuid }

%div
  %strong Date:
  = @special_event.datetime.strftime("%A, %B #{@special_event.datetime.day.ordinalize}")

%div
  %strong Time:
  = @special_event.datetime.strftime('%l:%M %p')

%div
  %strong End:
  = @special_event.datetime_end.strftime('%l:%M %p')

- if @address
  %div
    %strong Address:
    = @address.formatted_full_one_line

  %div
    - if @address.special_instructions && @address.special_instructions.length > 0
      %strong Special Instructions:
      = @address.special_instructions

%div
  %strong Description:
  %br
  %pre.special_event_description
    = sanitize(@special_event.description)

%div
  %strong Added:
  = "#{@special_event.added}"

%div
  %strong Invited:
  = "#{@special_event.invited}"

%div
  %strong Total Coming:
  = "#{@special_event.coming}"

%div
  %strong Invitees Coming:
  = "#{@special_event.invited_coming}"

%div
  %strong Plus Ones Coming:
  = "#{@special_event.plus_ones}"

%div
  %strong Maybe:
  = "#{@special_event.maybes}"

%div
  %strong Declined:
  = "#{@special_event.declined}"

%div
  %strong Not Responded:
  = "#{@special_event.unresponded}"

%div.special_events_form
  %br
  %strong Add Guests:

  = form_tag(special_event_add_guests_path, method: :post) do |f|
    = text_area_tag :addresses, @bad_addresses
    = submit_tag 'Add Guests'

%div.special_events_form
  -if @uninvited.length > 0
    %br
    %strong Not Yet Invited:
    %table
      %thead
        %th Email Address
        %th Invite
      %tbody
        - @uninvited.each do |guest|
          %tr
            %td
              = guest.email_address
            %td
              - if @special_event.datetime > DateTime.now
                = button_to 'Invite', special_invite_guest_path, method: :get, params: { special_event_id: @special_event.id, email_address: guest.email_address}
    - if @special_event.datetime > DateTime.now
      %br
      = button_to 'Invite Everyone!', special_invite_guests_path, method: :get, params: { special_event_id: @special_event.id }

  -if @invited.length > 0
    %br
    %strong Invited:
    %table
      %thead
        %th Email Address
        %th RSVP
      %tbody
        - @invited.each do |guest|
          %tr{class: ['rsvp', Rsvp::RESPONSE_STRINGS_BY_VALUE[guest.rsvp]]}
            %td
              = guest.email_address
            %td
              = form_tag(submit_special_event_rsvp_path) do |f|
                = select_tag 'RSVP', options_for_select(@options_for_rsvp_select, guest.rsvp), :onchange => 'this.form.submit()'
                = hidden_field(:guest, :email_address, :value => guest.email_address)

app/views/special_events/delete.html.haml
= render partial: 'admin_toolbar'

%p
  = link_to 'Back', controller: 'special_events', action: 'edit', uuid: @special_event.uuid

%strong Delete Special Event?

%div
  %strong Date:
  = @special_event.datetime.strftime("%A, %B #{@special_event.datetime.day.ordinalize}")

%div
  %strong Time:
  = @special_event.datetime.strftime('%l:%M %p')

%div
  %strong End:
  = @special_event.datetime_end.strftime('%l:%M %p')

- if @address
  %div
    %strong Address:
    = @address.formatted_full_one_line

  %div
    - if @address.special_instructions && @address.special_instructions.length > 0
      %strong Special Instructions:
      = @address.special_instructions

%div
  %strong Description:
  %br
  %pre.special_event_description
    = sanitize(@special_event.description)

%div
  %strong Total Event Guests:
  = "#{@special_event.invited}"

%div
  %strong Total Event Maybes:
  = "#{pluralize(@special_event.maybes, 'Maybe')}"

.form
  = form_tag(soft_delete_special_event_path(@special_event.uuid), method: 'delete') do
    .actions
      = submit_tag 'Delete'

app/views/special_events/deleted.html.haml
%h1 Special Event Deleted

%p This special event has been deleted.

app/views/special_events/edit.html.haml
= render partial: 'admin_toolbar'

%p
  = link_to 'Back', controller: 'special_events', action: 'index'

%h1 Edit Special Event

= render partial: 'special_event_form', locals: { special_event: @special_event, submit_url: update_special_event_path, edit: true }

app/views/special_events/index.html.haml
= render partial: 'admin_toolbar'

%p
  = link_to 'New Special Event', { controller: 'special_events', action: 'new' }

- if @upcoming_special_events.length > 0
  %h2 Upcoming Special Events
  = render partial: 'special_event_table', locals: { events: @upcoming_special_events.reverse(), editable: true }

- if @past_special_events.length > 0
  %h2 Past Special Events
  = render partial: 'special_event_table', locals: { events: @past_special_events, editable: false }

- if @deleted_special_events.length > 0
  %h2 Deleted Special Events
  = render partial: 'special_event_table', locals: { events: @deleted_special_events, editable: false }

app/views/special_events/new.html.haml
= render partial: 'admin_toolbar'

%p
  = link_to 'Back', controller: 'special_events', action: 'index'

%h1 New Special Event

= render partial: 'special_event_form', locals: { special_event: @special_event, submit_url: create_special_event_path, edit: false }